export const GET_QUOTES_SUCCESS = "GET_QUOTES_SUCCESS";
export const GET_QUOTES_ERROR = "GET_QUOTES_ERROR";
export const GET_CURRENT_QUOTE_SUCCESS = "GET_CURRENT_QUOTE_SUCCESS";
export const GET_CURRENT_QUOTE_ERROR = "GET_CURRENT_QUOTE_ERROR";
